/*************************************************************************
* 
* PURPOSE:  This is a Test Class for the CMDefaultBridge class
			
*         
* CLASS: CMDefaultBridgeTest
* CREATED: 06/05/2013 Ethos Solutions - www.ethos.com
* AUTHOR: Austin Delorme
**************************************************************************/
public with sharing class CMDefaultBridgeTest {
	public CMDefaultBridgeTest() {
		
	}
}