/*************************************************************************
*
* PURPOSE: Default Cost model Bridge class for Product Groups with
* no Cost Model
*
* CLASS: CMDefaultBridge
* CREATED: 7/18/13/2013 Ethos Solutions - www.ethos.com
* AUTHOR: Austin Delorme
***************************************************************************/
public with sharing class CMDefaultBridge extends CMBridgeBase
{}