/*************************************************************************
* 
* PURPOSE:  This is a Test Class for the CMDefaultBuilder class
			
*         
* CLASS: CMDefaultBuilderTest
* CREATED: 06/05/2013 Ethos Solutions - www.ethos.com
* AUTHOR: Austin Delorme
**************************************************************************/
public with sharing class CMDefaultBuilderTest {
	public CMDefaultBuilderTest() {
		
	}
}