/*************************************************************************
*
* PURPOSE: Calculate 3D wire length or 2D wire length based on 
* wireSize, numberOfWires, CM Version and wire length.
*
* CLASS: CMMLFWireCalc
* CREATED: 6/28/2013 Ethos Solutions - www.ethos.com
* AUTHOR: Chia Yuan Chuang
***************************************************************************/

public class CMMLFWireCalc extends CMWireCalcBase
{}