/*************************************************************************
* 
* PURPOSE: IRR calculation test methods for PBGA product group. 
* The whole test is based on PBGA Cost Model Excel Sheet
*          
* CLASS: CMPBGAIRRCalcTest
* CREATED: 06/27/2013 Ethos Solutions - www.ethos.com
* AUTHOR: Chia Yuan Chuang
* 
**************************************************************************/

@isTest
private class CMPBGAIRRCalcTest { 
	//no longer needed, irr testing moved to builder test in AMK-2263
}