global class CONDA02E1KONH {
	
    webservice String KNUMH {get; set;}
    webservice String DATAB {get; set;}
    webservice String DATBI {get; set;} 
    webservice String KOSRT {get; set;}
    webservice String KZUST {get; set;}
    webservice String KNUMA_PI {get; set;}
    webservice String KNUMA_AG {get; set;}
    webservice String KNUMA_SQ {get; set;}
    webservice String KNUMA_SD {get; set;}
    webservice String AKTNR {get; set;}
    webservice String KNUMA_BO {get; set;}
    webservice List<CONDA02E1KONP> E1KONP {get; set;}
    webservice String SEGMENT {get; set;}

}