global class CONDA02E1VFSCAH {
	
    webservice  String SCATYP {get; set;}
    webservice  String SCABAS {get; set;}
    webservice  String SCUOF {get; set;}
    webservice  String KPEIN {get; set;}
    webservice  String KMEIN {get; set;}
    webservice  String KRECH {get; set;}
    webservice  String LPEIN {get; set;}
    webservice  String SCALEN {get; set;}
    webservice  String TSCALEN {get; set;}
    webservice  String MINFLG {get; set;}
    webservice  String MAXFLG {get; set;}
    webservice  String CCBVRR {get; set;}
    webservice  String SCBVRR {get; set;}
    webservice  String CTBVRR {get; set;}
    webservice  String KAPPL {get; set;}
    webservice  String SCA_TXT {get; set;}
    webservice  String SPRAS {get; set;}
    webservice  List<CONDA02E1VFSCAIX> E1VFSCAIX {get; set;}
    webservice  String SEGMENT {get; set;}
}