/*************************************************************************
* 
* PURPOSE: Test methods for CPNLineItem 
*          
* CLASS: CPNLineItemTest
* CREATED: 03/19/2013 Ethos Solutions - www.ethos.com
* AUTHOR: Raghuveer Mandali
* 
**************************************************************************/
@isTest
private class CPNLineItemTest {/*
	
	/**
    * Tests constructor initialization for CPNLineItem
    *
    private static testmethod void testConstructor() {
    	Package_Family__c pk = SharedUnitTestUtils.createTestPackageFamily();
    	RFQItemWrapper item = SharedUnitTestUtils.createLineItem('Unit Test Package Family');
    	RFQI_PF_Field_Def__c fieldDef = SharedUnitTestUtils.createTestRFQIPFFieldDef();
    	CPNLineItem CPNLI = new CPNLineItem(item.specificRfqItem,item.wireConfigurations,item.packageFamily); 
    	system.assert(CPNLI != null);
        
    }
    
    /**
    * Tests ToString for CPNLineItem
    *
     private static testmethod void testToString(){
     	Package_Family__c pk = SharedUnitTestUtils.createTestPackageFamily();
     	RFQItemWrapper item = SharedUnitTestUtils.createLineItem('Unit Test Package Family');
     	RFQI_PF_Field_Def__c fieldDef = SharedUnitTestUtils.createTestRFQIPFFieldDef();
    	CPNLineItem CPNLI = new CPNLineItem(item.specificRfqItem,item.wireConfigurations,item.packageFamily); 
    	system.assert(CPNLI.toString() != null);
     }
     
    /**
    * Tests ToJSON for CPNLineItem
    *
     private static testmethod void testToJSON() {
     	Package_Family__c pk = SharedUnitTestUtils.createTestPackageFamily();
     	RFQItemWrapper item = SharedUnitTestUtils.createLineItem('Unit Test Package Family');
     	RFQI_PF_Field_Def__c fieldDef = SharedUnitTestUtils.createTestRFQIPFFieldDef();
    	CPNLineItem CPNLI = new CPNLineItem(item.specificRfqItem,item.wireConfigurations,item.packageFamily); 
    	system.assert(CPNLI.toJSON() != null);	    	
     }
     
    /**
    * Tests hashCode for CPNLineItem
    *
    private static testmethod void testHashCode() {
    	Package_Family__c pk = SharedUnitTestUtils.createTestPackageFamily();
    	RFQItemWrapper item = SharedUnitTestUtils.createLineItem('Unit Test Package Family');
    	RFQI_PF_Field_Def__c fieldDef = SharedUnitTestUtils.createTestRFQIPFFieldDef();
    	CPNLineItem CPNLI = new CPNLineItem(item.specificRfqItem,item.wireConfigurations,item.packageFamily);
    	system.assert(CPNLI.hashCode() != null); 
    }
    
    /**
    * Tests getNumberWireConfigs for CPNLineItem
    *
    private static testmethod void testGetNumberWireConfigs() {
    	Package_Family__c pk = SharedUnitTestUtils.createTestPackageFamily();
    	RFQItemWrapper item = SharedUnitTestUtils.createLineItem('Unit Test Package Family');
    	RFQI_PF_Field_Def__c fieldDef = SharedUnitTestUtils.createTestRFQIPFFieldDef();
    	CPNLineItem CPNLI = new CPNLineItem(item.specificRfqItem,item.wireConfigurations,item.packageFamily);
    	system.assert(CPNLI.getNumberWireConfigs() != null);
    }
*/}