/*************************************************************************
* 
* PURPOSE: Inner Parameter SD26DTPricingAttribute for 
*          SAPInterface.updatePricingAttribute created from 
*          SD26DTPricingAttribute.xsd each of these 
*          should be matched to an SF metadata value on 
*          a package family object.
*
* CLASS: ITEM
* CREATED: 03/12/2013 Ethos Solutions - www.ethos.com
* AUTHOR: Jason Swenski
* 
**************************************************************************/
global class ITEM {
	
	webservice String obj_name {get; set;}
	webservice String obj_value {get; set;}

}