public with sharing class OtherFieldHelper {
	public static Map<String, Map<String, List<String>>> otherFieldMaps = new Map<String, Map<String, List<String>>>
	{
		'RFQI_fcCSP__c.Lid__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'Lid_Size_X__c', 'Lid_Size_Y__c', 'Lid_Attach_Type__c', 'Lid_Material__c', 'Lid_Finish__c', 'Lid_TIM__c', 'Lid_Adhesive__c', 'Prestacking__c'}
		},

		'RFQI_fcCSP__c.Include_TMV__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'Number_of_TMV_Balls__c', 'TMV_Pitch__c', 'TMV_Ball_Composition__c'}
		},
		'RFQI_fcCSP__c.Lid_Attach_Type__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lid_Attach_Type_Other__c'}
		},
		'RFQI_fcCSP__c.Lid_Material__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lid_Material_Other__c'}
		},
		'RFQI_fcCSP__c.Lid_Finish__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lid_Finish_Other__c'}
		},
		'RFQI_fcCSP__c.Lid_TIM__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lid_TIM_Other__c'}
		},
		'RFQI_fcCSP__c.Lid_Adhesive__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lid_Adhesive_Other__c'}
		},
		'RFQI_fcCSP__c.TMV_Ball_Composition__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'TMV_Ball_Composition_Other__c'}
		},
		'RFQI_fcCSP__c.Strip_Width__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Strip_Width_Other__c'}
		},
		'RFQI_fcCSP__c.BGA_Ball_Composition__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'BGA_Ball_Composition_Other__c'}
		},
		'RFQI_fcCSP__c.Solder_Mask_Dam__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'Substrate_Dam_Material__c', 'Substrate_Dam_Thickness__c'}
		},
		'RFQIPC_fcCSP__c.Passive_Type__c' =>
		new Map<String, List<String>>
		{
			'capacitor' => new List<String> {'Capacitance__c', 'Voltage_Other__c', 'Dielectric_Material__c'},
			'resistor' => new List<String> {'Resistance_Value__c', 'Power__c'},
			'inductor' => new List<String> {'Inductance__c', 'Amperage__c'},
			'other' => new List<String> {'Passive_Type_Other__c'}
		},
		'RFQIPC_fcCSP__c.Specific_Passive__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Passive_Size_Other__c'}
		},
		'RFQIPC_fcCSP__c.Tolerance__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Tolerance_Other__c'}
		},
		'RFQIPC_fcCSP__c.Voltage_Other__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Voltage__c'}
		},
		'RFQIPC_fcCSP__c.Power__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Power_Other__c'}
		},
		'RFQIPC_fcCSP__c.Dielectric_Material__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Dielectric_Material_Other__c'}
		},
		'RFQIPC_fcCSP__c.Passive_Supplier__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Passive_Supplier_Other__c'}
		},
		'RFQIPC_fcCSP__c.Amkor_SID__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Amkor_SID_Other__c'}
		},
		'RFQIPC_fcCSP__c.Supplier_SID_Part_Number__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Supplier_SID_Part_Number_Other__c'}
		},
		'RFQIDC_fcCSP__c.Passivation_Type__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Passivation_Type_Other__c'}
		},
		'RFQI_FCSCSP__c.Lid__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'Lid_Size_X__c', 'Lid_Size_Y__c', 'Lid_Attach_Type__c', 'Lid_Material__c', 'Lid_Finish__c', 'Lid_TIM__c', 'Lid_Adhesive__c', 'Prestacking__c'}
		},
		'RFQI_FCSCSP__c.Include_TMV__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'Number_of_TMV_Balls__c', 'TMV_Pitch__c', 'TMV_Ball_Composition__c'}
		},
		'RFQI_FCSCSP__c.Lid_Attach_Type__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lid_Attach_Type_Other__c'}
		},
		'RFQI_FCSCSP__c.Lid_Material__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lid_Material_Other__c'}
		},
		'RFQI_FCSCSP__c.Lid_Finish__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lid_Finish_Other__c'}
		},
		'RFQI_FCSCSP__c.Lid_TIM__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lid_TIM_Other__c'}
		},
		'RFQI_FCSCSP__c.Lid_Adhesive__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lid_Adhesive_Other__c'}
		},
		'RFQI_FCSCSP__c.TMV_Ball_Composition__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'TMV_Ball_Composition_Other__c'}
		},
		'RFQI_FCSCSP__c.Strip_Width__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Strip_Width_Other__c'}
		},
		'RFQI_FCSCSP__c.BGA_Ball_Composition__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'BGA_Ball_Composition_Other__c'}
		},
		'RFQI_FCSCSP__c.Solder_Mask_Dam__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'Substrate_Dam_Material__c', 'Substrate_Dam_Thickness__c'}
		},
		'RFQIDC_FCSCSP__c.Passivation_Type__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Passivation_Type_Other__c'}
		},
		'RFQIWC_FCSCSP__c.Wire_Diameter__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Wire_Diameter_Other__c'}
		},
		'RFQIPC_FCSCSP__c.Passive_Type__c' =>
		new Map<String, List<String>>
		{
			'capacitor' => new List<String> {'Capacitance__c', 'Voltage_Other__c', 'Dielectric_Material__c'},
			'resistor' => new List<String> {'Resistance_Value__c', 'Power__c'},
			'inductor' => new List<String> {'Inductance__c', 'Amperage__c'},
			'other' => new List<String> {'Passive_Type_Other__c'}
		},
		'RFQIPC_FCSCSP__c.Specific_Passive__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Passive_Size_Other__c'}
		},
		'RFQIPC_FCSCSP__c.Tolerance__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Tolerance_Other__c'}
		},
		'RFQIPC_FCSCSP__c.Voltage_Other__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Voltage__c'}
		},
		'RFQIPC_FCSCSP__c.Power__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Power_Other__c'}
		},
		'RFQIPC_FCSCSP__c.Dielectric_Material__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Dielectric_Material_Other__c'}
		},
		'RFQIPC_FCSCSP__c.Passive_Supplier__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Passive_Supplier_Other__c'}
		},
		'RFQIPC_FCSCSP__c.Amkor_SID__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Amkor_SID_Other__c'}
		},
		'RFQIPC_FCSCSP__c.Supplier_SID_Part_Number__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Supplier_SID_Part_Number_Other__c'}
		},
		'RFQIWC_FCSCSP__c.Wire_Diameter__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Wire_Diameter_Other__c'}
		},
		'RFQI_fcBGA__c.Lid__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'TIM__c'}
		},
		'RFQI_fcBGA__c.Package_Structure__c' =>
		new Map<String, List<String>>
		{
			'null' => new List<String> {'Lid__c', 'Ground_Lid_Adhesive__c', 'HS_Adhesive__c', 'Stiffener_Adhesive__c'},
			'1-pc lid' => new List<String> {'Lid__c', 'Ground_Lid_Adhesive__c', 'HS_Adhesive__c', 'Stiffener_Adhesive__c', 'Lid_Attach_Type__c', 'Lid_Thickness__c'},
			'2-pc lid' => new List<String> {'Lid__c', 'Ground_Lid_Adhesive__c', 'HS_Adhesive__c', 'Stiffener_Adhesive__c', 'Lid_Attach_Type__c', 'Lid_Thickness__c'},
			'stiffener only' => new List<String> {'Lid__c', 'Ground_Lid_Adhesive__c', 'HS_Adhesive__c', 'Stiffener_Adhesive__c'},
			'fcmbga' => new List<String> {'Lid__c', 'Ground_Lid_Adhesive__c', 'HS_Adhesive__c', 'Stiffener_Adhesive__c'}
		},
		'RFQIPC_fcBGA__c.Passive_Type__c' =>
		new Map<String, List<String>>
		{
			'capacitor' => new List<String> {'Capacitance__c', 'Voltage_Other__c', 'Dielectric_Material__c'},
			'resistor' => new List<String> {'Resistance_Value__c', 'Power__c'},
			'inductor' => new List<String> {'Inductance__c', 'Amperage__c'},
			'other' => new List<String> {'Passive_Type_Other__c'}
		},
		'RFQIPC_fcBGA__c.Specific_Passive__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Passive_Size_Other__c'}
		},
		'RFQIPC_fcBGA__c.Tolerance__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Tolerance_Other__c'}
		},
		'RFQIPC_fcBGA__c.Voltage_Other__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Voltage__c'}
		},
		'RFQIPC_fcBGA__c.Power__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Power_Other__c'}
		},
		'RFQIPC_fcBGA__c.Dielectric_Material__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Dielectric_Material_Other__c'}
		},
		'RFQIPC_fcBGA__c.Passive_Supplier__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Passive_Supplier_Other__c'}
		},
		'RFQIPC_fcBGA__c.Amkor_SID__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Amkor_SID_Other__c'}
		},
		'RFQIPC_fcBGA__c.Supplier_SID_Part_Number__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Supplier_SID_Part_Number_Other__c'}
		},
		'Passives.Passive_Type__c' =>
		new Map<String, List<String>>
		{
			'capacitor' => new List<String> {'Capacitance__c', 'Voltage_Other__c', 'Dielectric_Material__c'},
			'resistor' => new List<String> {'Resistance_Value__c', 'Power__c'},
			'inductor' => new List<String> {'Inductance__c', 'Amperage__c'},
			'other' => new List<String> {'Passive_Type_Other__c'}
		},
		'Passives.Specific_Passive__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Passive_Size_Other__c'}
		},
		'Passives.Tolerance__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Tolerance_Other__c'}
		},
		'Passives.Voltage_Other__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Voltage__c'}
		},
		'Passives.Power__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Power_Other__c'}
		},
		'Passives.Dielectric_Material__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Dielectric_Material_Other__c'}
		},
		'Passives.Passive_Supplier__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Passive_Supplier_Other__c'}
		},
		'Passives.Amkor_SID__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Amkor_SID_Other__c'}
		},
		'Passives.Supplier_SID_Part_Number__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Supplier_SID_Part_Number_Other__c'}
		},
		'RFQI_CABGA__c.Body_Size_Z__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Body_Z__c'}
		},
		'RFQI_Electrical_Service__c.Electrical_Services__c' =>
		new Map<String, List<String>>
		{
			'electrical design (co-design)' => new List<String> {'Package_Description_Extended__c'},
			'other services ( pop, sip, tsv, hybrid, etc..)' => new List<String> {'Package_Description_Extended__c'},
			'current density analysis' => new List<String> {'Package_Description_Extended__c'},
			'emi / radiation analysis' => new List<String> {'Package_Description_Extended__c'},
			'ir drop analysis' => new List<String> {'Substrate__c', 'Number_of_Power_Domains__c', 'Design_Request_Number__c'},
			'power integrity analysis (f, t domain)' => new List<String> {'Substrate__c', 'Time_or_Frequency_Domain__c', 'Number_of_Power_Domains__c', 'Design_Request_Number__c'},
			's-parameter extraction' => new List<String> {'Substrate__c', 'Number_of_Layers__c', 'Number_of_Signal_Wirebonds__c', 'Number_of_Signal_Bumps__c', 'Design_Request_Number__c'},
			'parallel bus analysis (ssn, io supply collapse)' => new List<String> {'Substrate__c', 'Bus_Width__c', 'Simulation_Direction__c', 'Process_Corner__c', 'Design_Request_Number__c'},
			'serial link (channel) analysis' => new List<String> {'Substrate__c', 'Number_of_Lanes__c', 'Simulation_Direction_SLA__c', 'Buffer_Model_Type__c', 'Design_Request_Number__c'},
			'3d rlc extraction' => new List<String> {'Substrate__c', 'Number_of_Die__c', 'Number_of_Balls__c', 'Number_of_Wirebonds__c', 'Design_Request_Number__c', 'Number_of_Bumps_PK__c'}
		},
		'RFQI_Final__c.Tester_Model_PK__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Tester_Model_PK_Other__c'}
		},
		'RFQIIC_Final__c.Tester_Model__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Tester_Model_Other__c'}
		},
		'RFQI_Final__c.Handler_Model_PK__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Handler_Model_PK_Other__c'}
		},
		'RFQIIC_Final__c.Handler_Model__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Handler_Model_Other__c'}
		},

		'RFQI_Wafer__c.Tester_Model_PK__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Tester_Model_PK_Other__c'}
		},
		'RFQIIC_Wafer__c.Tester_Model__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Tester_Model_Other__c'}
		},
		'RFQI_Wafer__c.Handler_Model_PK__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Handler_Model_PK_Other__c'}
		},
		'RFQIIC_Wafer__c.Handler_Model__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Handler_Model_Other__c'}
		},
		'RFQI_TESTS__c.Competitor__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Competitor_Other__c'},
			'multiple' => new List<String> {'Competitors__c'}
		},
		'RFQI_TESTS__c.Test_Type__c' =>
		new Map<String, List<String>>
		{
			'wafer probe' => new List<String> {'Wafer_Size_PK__c', 'GDPW_PK__c'}
		},
		'RFQIIC_TESTS__c.Handler_Model__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Handler_Model_Other__c'}
		},
		'RFQIIC_TESTS__c.Tester_Model__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Tester_Model_Other__c'}
		},
		'RFQI_TESTS__c.Wafer_Bake__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'Wafer_Bake_Time__c', 'BU_Price_Wafer_Bake__c'}
		},
		'RFQI_TESTS__c.Wafer_Packing__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'Packing_Method_Wafer__c', 'BU_Price_Wafer_Packing__c'}
		},

		'RFQI_TESTS__c.Scan__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_Lead_Scan__c'}
		},
		'RFQI_TESTS__c.Tape_and_Reel__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_Tape_and_Reel__c'}
		},
		'RFQI_TESTS__c.Ink_Mark__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_Ink_Mark__c'}
		},
		'RFQI_TESTS__c.Laser_Mark__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_Laser_Mark__c'}
		},
		'RFQI_TESTS__c.Drop_Ship__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_Drop_Ship__c'}
		},
		'RFQI_TESTS__c.De_Tape__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_De_Tape__c'}
		},
		'RFQI_TESTS__c.Bake__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_Bake__c'}
		},
		'RFQI_TESTS__c.Offline_Ink_Mark__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_Offline_Ink_Mark__c'}
		},
		'RFQI_TESTS__c.Other__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_Other__c'}
		},
		'RFQI_TESTS__c.Packing_Method__c' =>
		new Map<String, List<String>>
		{
			'trays' => new List<String> {'BU_Price_Pack__c'},
			'tubes' => new List<String> {'BU_Price_Pack__c'},
			't&r' => new List<String> {'BU_Price_Pack__c'}
		},
		'RFQI_TESTS__c.Burn_In__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_Burn_In__c'}
		},
		'RFQI_TESTS__c.Dry_Pack__c' =>
		new Map<String, List<String>>
		{
			'true' => new List<String> {'BU_Price_Dry_Pack__c'}
		},
		'RFQI_PUNCH_DUAL_ROW_MLF__c.Lead_Pitch__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lead_Count_Other__c', 'Pitch_Other__c'}
		},
		'RFQI_PUNCH_DUAL_ROW_DFN__c.Lead_Pitch__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lead_Count_Other__c', 'Pitch_Other__c'}
		},
		'RFQI_PUNCH_SINGLE_ROW_MLF__c.Lead_Pitch__c' =>
		new Map<String, List<String>>
		{
			'other' => new List<String> {'Lead_Count_Other__c', 'Pitch_Other__c'}
		}
			
	};
	private OtherFieldHelper() {}

	//AMK-1794, all these pfs were cloned from FC passives so they started with the same other fields
	private static Set<String> passiveFamilies = new Set<String>
	{
		'RFQIPC_TQFP__c',
		'RFQIPC_LQFP__c',
		'RFQIPC_MQFP__c',
		'RFQIPC_PLCC__c',
		'RFQIPC_PowerQuad_4__c',
		'RFQIPC_tsCSP__c',
		'RFQIPC_MQFP_Heat_Spreader__c',
		'RFQIPC_Fusion_Quad__c',
		'RFQIPC_MQFP_FCIR__c',
		'RFQIPC_SCSP__c',
		'RFQIPC_PBGA__c',
		'RFQIPC_DLP__c',
		'RFQIPC_AREA_SENSOR__c',
		'RFQIPC_CABGA__c',
		'RFQIPC_SBGA__c',
		'RFQIPC_TA_FLEX_BGA__c',
		'RFQIPC_TABGA__c',
		'RFQIPC_CCD_IMAGE__c'
	};

	public static String getOtherMapStringForField(String packageFamily, String fieldName) {
		String key = passiveFamilies.contains(packageFamily) ? 'Passives' : packageFamily;
		String fullFieldName = key + '.' + fieldName;

		if (otherFieldMaps.containsKey(fullFieldName)) {
			Map<String, List<String>> otherValues = otherFieldMaps.get(fullFieldName);
			String jsonVal = System.JSON.serialize(otherValues);

			System.debug('### Found Other values: ' + jsonVal); 

			return jsonVal;
		}

		return null;
	}

	/*public static Set<String> getOtherFields(RFQItemWrapper wrapper) {
		List<RFQISectionAttribute> otherAttributes = wrapper.layout.getOtherFieldAttributes();
		Set<String> valOtherFields = new Set<String>();

		if (otherAttributes.size() > 0) {
			for (RFQISectionAttribute attribute : otherAttributes) {
				Object itemVal = wrapper.specificRfqItem.get(attribute.fieldAPIName);

				if (itemVal != null && attribute.otherFields.containsKey(String.valueOf(itemVal))) {
					valOtherFields = attribute.otherFields.get(String.valueOf(itemVal));
				}
				return valOtherFields;

			}
		}
		return null;
	}*/
}