@isTest
public class RFQICreateVolumeCloneControllerTest {
    public static testmethod void createclonetest(){
        //RFQICreateVolumeCloneController clonecont = new RFQICreateVolumeCloneController();
        
        /*RFQ__c rfq = SharedUnitTestUtils.createTestRFQ();
        PageReference pageRef = Page.RFQICreateVolumeClone;
        Test.setCurrentPage(pageRef);
        
        PageUtil.putParam('rfqId',rfq.Id);
        clonecont.createClones();*/
    }
}