@isTest
private class RFQSystemSettingsTest {
    
    //Move SystemSettings setup to AdminInstaller, when that is done these 
    //can be uncommented
    private static testmethod void testCS() {
        //System.Assert(RFQSystemSettings.getBUPricer() == null);
        //System.Assert(RFQSystemSettings.getBUPricer() == 'BU Pricer');
        //System.Assert(RFQSystemSettings.getSalesManagement() == 'Sales Management');
        //System.Assert(RFQSystemSettings.getSalesTeam() == 'Sales Team');
    }

}