/*************************************************************************
*
* PURPOSE: Access the SAP Gold Base Object
*
* CLASS: 
* CREATED: 7/21/2013 Ethos Solutions - www.ethos.com
* AUTHOR: Austin Delorme
***************************************************************************/  
public with sharing class SAPGoldBaseDao 
{
    /*
    private static final SAPGoldBaseDao dao = new SAPGoldBaseDao();
 
    private SAPGoldBaseDao(){  super('SAP_Gold_Base__c'); }
    
    public static SAPGoldBaseDao getInstance() {
        return dao;
    }
    
    public SAP_Gold_Base__c getById(String recordId) {
        return (SAP_Gold_Base__c)getSObjectById(recordId); 
    }

    public List<SAP_Gold_Base__c> getByAccountAndNewest(String accountId)
    {
    	return (List<SAP_Gold_Base__c>)getSobjects('Account__c = ' + quote(accountId) + ' AND Newest__c = true');
    }*/
}