/*************************************************************************
* 
* PURPOSE: Parameter for SAPInterface.updatePricingAttribute
*          created from SD26DTPricingAttribute.xsd
*
* CLASS: SD26DTPricingAttribute
* CREATED: 03/12/2013 Ethos Solutions - www.ethos.com
* AUTHOR: Jason Swenski
* 
**************************************************************************/
global class SD26DTPricingAttribute {
	
	webservice List<ITEM> item {get; set;}

}