global class ZIDEBMASEXTE1T023X {

    webservice String MSGFN {get;set;}
    webservice String LOCNR {get;set;}
    webservice String MATNR {get;set;}
    webservice String WMATN {get;set;}
    webservice String MATKL {get;set;}
    webservice String MATNREXTERNAL {get;set;}
    webservice String MATNRVERSION {get;set;}
    webservice String MATNRGUID {get;set;}
    webservice String WMATNEXTERNAL {get;set;}
    webservice String WMATNVERSION {get;set;}
    webservice String WMATNGUID {get;set;}
    webservice String SEGMENT {get;set;}

}