@isTest

public class ZIDEBMASEXTE1WRF1MTest{

     public static testMethod void testZIDEBMASEXTE1WRF1M(){
            ZIDEBMASEXTE1WRF1M instance = new ZIDEBMASEXTE1WRF1M();
            instance.MSGFN = instance.MSGFN;
            instance.LOCNR = instance.LOCNR;
            instance.EROED = instance.EROED;
            instance.SCHLD = instance.SCHLD;
            instance.SPDAB = instance.SPDAB;
            instance.SPDBI = instance.SPDBI;
            instance.AUTOB = instance.AUTOB;
            instance.KOPRO = instance.KOPRO;
            instance.LAYVR = instance.LAYVR;
            instance.FLVAR = instance.FLVAR;
            instance.STFAK = instance.STFAK;
            instance.WANID = instance.WANID;
            instance.MOAB1 = instance.MOAB1;
            instance.MOBI1 = instance.MOBI1;
            instance.MOAB2 = instance.MOAB2;
            instance.MOBI2 = instance.MOBI2;
            instance.DIAB1 = instance.DIAB1;
            instance.DIBI1 = instance.DIBI1;
            instance.DIAB2 = instance.DIAB2;
            instance.DIBI2 = instance.DIBI2;
            instance.MIAB1 = instance.MIAB1;
            instance.MIBI1 = instance.MIBI1;
            instance.MIAB2 = instance.MIAB2;
            instance.MIBI2 = instance.MIBI2;
            instance.DOAB1 = instance.DOAB1;
            instance.DOBI1 = instance.DOBI1;
            instance.DOAB2 = instance.DOAB2;
            instance.DOBI2 = instance.DOBI2;
            instance.FRAB1 = instance.FRAB1;
            instance.FRBI1 = instance.FRBI1;
            instance.FRAB2 = instance.FRAB2;
            instance.FRBI2 = instance.FRBI2;
            instance.SAAB1 = instance.SAAB1;
            instance.SABI1 = instance.SABI1;
            instance.SAAB2 = instance.SAAB2;
            instance.SABI2 = instance.SABI2;
            instance.SOAB1 = instance.SOAB1;
            instance.SOBI1 = instance.SOBI1;
            instance.SOAB2 = instance.SOAB2;
            instance.SOBI2 = instance.SOBI2;
            instance.VERFL = instance.VERFL;
            instance.VERFE = instance.VERFE;
            instance.SPGR1 = instance.SPGR1;
            instance.INPRO = instance.INPRO;
            instance.EKOAR = instance.EKOAR;
            instance.KZLIK = instance.KZLIK;
            instance.BETRP = instance.BETRP;
            instance.ERDAT = instance.ERDAT;
            instance.ERNAM = instance.ERNAM;
            instance.NLMATFB = instance.NLMATFB;
            instance.BWWRK = instance.BWWRK;
            instance.BWVKO = instance.BWVKO;
            instance.BWVTW = instance.BWVTW;
            instance.BBPRO = instance.BBPRO;
            instance.VKBURWRK = instance.VKBURWRK;
            instance.VLFKZ = instance.VLFKZ;
            instance.LSTFL = instance.LSTFL;
            instance.LIGRD = instance.LIGRD;
            instance.VKORG = instance.VKORG;
            instance.VTWEG = instance.VTWEG;
            instance.DESROI = instance.DESROI;
            instance.TIMINC = instance.TIMINC;
            instance.POSWS = instance.POSWS;
            instance.SSOPTPRO = instance.SSOPTPRO;
            instance.WBPRO = instance.WBPRO;
            instance.SEGMENT = instance.SEGMENT;
        

   }
}