global class ZIDEBMASEXTE1KNB5M {

    webservice String MSGFN {get;set;}
    webservice String MABER {get;set;}
    webservice String MAHNA {get;set;}
    webservice String MANSP {get;set;}
    webservice String MADAT {get;set;}
    webservice String MAHNS {get;set;}
    webservice String KNRMA {get;set;}
    webservice String GMVDT {get;set;}
    webservice String BUSAB {get;set;}
    webservice String SEGMENT {get;set;}

}