global class ZIDEBMASEXTE1KNBKM {

    webservice String MSGFN {get;set;}
    webservice String BANKS {get;set;}
    webservice String BANKL {get;set;}
    webservice String BANKN {get;set;}
    webservice String BKONT {get;set;}
    webservice String BVTYP {get;set;}
    webservice String XEZER {get;set;}
    webservice String BKREF {get;set;}
    webservice String BANKA {get;set;}
    webservice String STRAS {get;set;}
    webservice String ORT01 {get;set;}
    webservice String BGRUP {get;set;}
    webservice String XPGRO {get;set;}
    webservice String BNKLZ {get;set;}
    webservice String PSKTO {get;set;}
    webservice String BRNCH {get;set;}
    webservice String PROVZ {get;set;}
    webservice String KOINH {get;set;}
    webservice String KOINHN {get;set;}
    webservice String KOVON {get;set;}
    webservice String KOBIS {get;set;}
    webservice String SEGMENT {get;set;}

}