global class ZIDEBMASEXTE1WRF6M {

    webservice String MSGFN {get;set;}
    webservice String LOCNR {get;set;}
    webservice String MATKL {get;set;}
    webservice String SSTUF {get;set;}
    webservice String SORBR {get;set;}
    webservice String ABTNR {get;set;}
    webservice String PRIOT {get;set;}
    webservice String DISPR {get;set;}
    webservice String PROPR {get;set;}
    webservice String PRIMW {get;set;}
    webservice String UPROF {get;set;}
    webservice String WDAUS {get;set;}
    webservice String RQGRP {get;set;}
    webservice String FBPRO {get;set;}
    webservice String PLTYPP {get;set;}
    webservice String PSTRA {get;set;}
    webservice String MGINT {get;set;}
    webservice String SEGMENT {get;set;}

}