global class ZIDEBMASEXTE1KNVAM {

    webservice String MSGFN {get;set;}
    webservice String ABLAD {get;set;}
    webservice String KNFAK {get;set;}
    webservice String WANID {get;set;}
    webservice String MOAB1 {get;set;}
    webservice String MOBI1 {get;set;}
    webservice String MOAB2 {get;set;}
    webservice String MOBI2 {get;set;}
    webservice String DIAB1 {get;set;}
    webservice String DIBI1 {get;set;}
    webservice String DIAB2 {get;set;}
    webservice String DIBI2 {get;set;}
    webservice String MIAB1 {get;set;}
    webservice String MIBI1 {get;set;}
    webservice String MIAB2 {get;set;}
    webservice String MIBI2 {get;set;}
    webservice String DOAB1 {get;set;}
    webservice String DOBI1 {get;set;}
    webservice String DOAB2 {get;set;}
    webservice String DOBI2 {get;set;}
    webservice String FRAB1 {get;set;}
    webservice String FRBI1 {get;set;}
    webservice String FRAB2 {get;set;}
    webservice String FRBI2 {get;set;}
    webservice String SAAB1 {get;set;}
    webservice String SABI1 {get;set;}
    webservice String SAAB2 {get;set;}
    webservice String SABI2 {get;set;}
    webservice String SOAB1 {get;set;}
    webservice String SOBI1 {get;set;}
    webservice String SOAB2 {get;set;}
    webservice String SOBI2 {get;set;}
    webservice String DEFAB {get;set;}
    webservice String SEGMENT {get;set;}

}