global class ZIDEBMASEXTE1T023W {

    webservice String MSGFN {get;set;}
    webservice String LOCNR {get;set;}
    webservice String MATKL {get;set;}
    webservice String WWGPA {get;set;}
    webservice String KEDET {get;set;}
    webservice String WWGPAEXTERNAL {get;set;}
    webservice String WWGPAVERSION {get;set;}
    webservice String WWGPAGUID {get;set;}
    webservice String SEGMENT {get;set;}

}