global class ZIDEBMASEXTE1VCKUN {

    webservice String MSGFN {get;set;}
    webservice String CCINS {get;set;}
    webservice String CCNUM {get;set;}
    webservice String CCDEF {get;set;}
    webservice String CCNAME {get;set;}
    webservice String DATAB {get;set;}
    webservice String DATBI {get;set;}
    webservice String CCTYP {get;set;}
    webservice String CCLOCK {get;set;}
    webservice String SEGMENT {get;set;}

}