global class ZIDEBMASEXTE1KNKKM {

    webservice String MSGFN {get;set;}
    webservice String KKBER {get;set;}
    webservice String KLIMK {get;set;}
    webservice String KNKLI {get;set;} 
    webservice String CTLPC {get;set;}
    webservice String DTREV {get;set;}
    webservice String CRBLB {get;set;}
    webservice String SBGRP {get;set;}
    webservice String NXTRV {get;set;}
    webservice String KRAUS {get;set;}
    webservice String PAYDB {get;set;}
    webservice String DBRAT {get;set;}
    webservice String REVDB {get;set;}
    webservice String GRUPP {get;set;}
    webservice String SBDAT {get;set;}
    webservice String KDGRP {get;set;}
    webservice String DBPAY {get;set;}
    webservice String DBRTG {get;set;}
    webservice String DBEKR {get;set;}
    webservice String DBWAE {get;set;}
    webservice String DBMON {get;set;}
    webservice List<ZIDEBMASEXTE1KNKKH> E1KNKKH {get;set;}
    webservice String SEGMENT {get;set;}

}