global class ZIDEBMASEXTE1KNKKH {

    webservice String MSGFN {get;set;}
    webservice String TDOBJECT {get;set;}
    webservice String TDNAME {get;set;}
    webservice String TDID {get;set;}
    webservice String TDSPRAS {get;set;}
    webservice String TDTEXTTYPE {get;set;}
    webservice String TDSPRASISO {get;set;}
    webservice List<ZIDEBMASEXTE1KNKKL> E1KNKKL {get;set;}
    webservice String SEGMENT {get;set;}

}