global class ZIDEBMASEXTE1WRF3M {

    webservice String MSGFN {get;set;}
    webservice String LOCNR {get;set;}
    webservice String MATKL {get;set;}
    webservice String DATBI {get;set;}
    webservice String DATAB {get;set;}
    webservice String LOCLB {get;set;}
    webservice String PRIORITAET {get;set;}
    webservice String TRANSPORTCHAIN {get;set;}
    webservice String SEGMENT {get;set;}

}