@isTest

public class ZIDEBMASEXTE1KNVKMTest{

     public static testMethod void testZIDEBMASEXTE1KNVKM(){
            ZIDEBMASEXTE1KNVKM instance = new ZIDEBMASEXTE1KNVKM();
            instance.MSGFN = instance.MSGFN ;
            instance.PARNR = instance.PARNR ;
            instance.NAMEV = instance.NAMEV ;
            instance.NAME1 = instance.NAME1 ;
            instance.ABTPA = instance.ABTPA ;
            instance.ABTNR = instance.ABTNR ;
            instance.UEPAR = instance.UEPAR ;
            instance.TELF1 = instance.TELF1 ;
            instance.ANRED = instance.ANRED ;
            instance.PAFKT = instance.PAFKT ;
            instance.PARVO = instance.PARVO ;
            instance.PAVIP = instance.PAVIP ;
            instance.PARGE = instance.PARGE ;
            instance.PARLA = instance.PARLA ;
            instance.GBDAT = instance.GBDAT ;
            instance.VRTNR = instance.VRTNR ;
            instance.BRYTH = instance.BRYTH ;
            instance.AKVER = instance.AKVER ;
            instance.NMAIL = instance.NMAIL ;
            instance.PARAU = instance.PARAU ;
            instance.PARH1 = instance.PARH1 ;
            instance.PARH2 = instance.PARH2 ;
            instance.PARH3 = instance.PARH3 ;
            instance.PARH4 = instance.PARH4 ;
            instance.PARH5 = instance.PARH5 ;
            instance.MOAB1 = instance.MOAB1 ;
            instance.MOBI1 = instance.MOBI1 ;
            instance.MOAB2 = instance.MOAB2 ;
            instance.MOBI2 = instance.MOBI2 ;
            instance.DIAB1 = instance.DIAB1 ;
            instance.DIBI1 = instance.DIBI1 ;
            instance.DIAB2 = instance.DIAB2 ;
            instance.DIBI2 = instance.DIBI2 ;
            instance.MIAB1 = instance.MIAB1 ;
            instance.MIBI1 = instance.MIBI1 ;
            instance.MIAB2 = instance.MIAB2 ;
            instance.MIBI2 = instance.MIBI2 ;
            instance.DOAB1 = instance.DOAB1 ;
            instance.DOBI1 = instance.DOBI1 ;
            instance.DOAB2 = instance.DOAB2 ;
            instance.DOBI2 = instance.DOBI2 ;
            instance.FRAB1 = instance.FRAB1 ;
            instance.FRBI1 = instance.FRBI1 ;
            instance.FRAB2 = instance.FRAB2 ;
            instance.FRBI2 = instance.FRBI2 ;
            instance.SAAB1 = instance.SAAB1 ;
            instance.SABI1 =  instance.SABI1 ; 
            instance.SAAB2 = instance.SAAB2 ;
            instance.SABI2 = instance.SABI2 ;
            instance.SOAB1 = instance.SOAB1 ;
            instance.SOBI1 = instance.SOBI1 ;
            instance.SOAB2 = instance.SOAB2 ;
            instance.SOBI2 = instance.SOBI2 ;
            instance.PAKN1 = instance.PAKN1 ;
            instance.PAKN2 = instance.PAKN2 ;
            instance.PAKN3 = instance.PAKN3 ;
            instance.PAKN4 = instance.PAKN4 ;
            instance.PAKN5 = instance.PAKN5 ;
            instance.SORTL = instance.SORTL ;
            instance.FAMST = instance.FAMST ;
            instance.SPNAM = instance.SPNAM ;
            instance.TITELAP = instance.TITELAP ;
            instance.PARLAISO = instance.PARLAISO ;
            instance.E1KNVKH = instance.E1KNVKH ;
            instance.SEGMENT = instance.SEGMENT ;

   }
}