global class ZIDEBMASEXTE1KNA11 {

    webservice String KNURL {get; set;}
    webservice String J_1KFREPRE {get; set;}
    webservice String J_1KFTBUS {get; set;}
    webservice String J_1KFTIND {get; set;}
    webservice String PSOIS {get; set;}
    webservice String PSON1 {get; set;}
    webservice String PSON2 {get; set;}
    webservice String PSON3 {get; set;}
    webservice String PSOVN {get; set;}
    webservice String PSOTL {get; set;}
    webservice String PSOO1 {get; set;}
    webservice String PSOO2 {get; set;} 
    webservice String PSOO3 {get; set;}
    webservice String PSOO4 {get; set;}
    webservice String PS005 {get; set;}
    webservice ZIDEBMASEXTZISKKATR ZISKKATR {get; set;}
    webservice String SEGMENT {get; set;}
}